# Site settings
title: 柳伟卫的个人网站 Way Lau's Personal Site - 关注编程、系统架构、性能优化
name: 柳伟卫的个人网站 Way Lau's Personal Site
url: "http://waylau.com"
email: waylau521@gmail.com
description: 柳伟卫的个人网站 Way Lau's Personal Site - 关注编程、系统架构、性能优化 | waylau.com
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: waylau521
github_username:  waylau
weibo_username: waylau521
facebook_username: waylau521
duoshuo_username: waylau
baidushare_id: 89860593
baidutongji_id: 28cf5fa48a599e39c5cc760931de942f
rss_url: "/feed.xml"
logo_image: "/images/logo.png"
# Build settings
gems: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
